### ISSUE TITLE
DB에 수집한 데이터 저장하기

### ISSUE THREAD

**Issue by wisdom08** [your-news/service-repo#11]
1. 정규화한 총 8개의 테이블을 사용하여 DB에 저장.
    - 엑셀 데이터의 각 row 당 insert sql문의 수가 너무 많아 200건의 기사를 넣는데 약 10분의 시간이 걸려 역정규화하여 데이터 보관하기로 의사결정
2. 최종으로 역정규화하여 News, Section(대분류), Division(중분류) 3개의 테이블로 변경
3. Amazon RDS에 직접 넣는 방법 또한 효율적이지 못하다고 판단하여 다른 방안을 찾음
    - MySQL 마이그레이션 기능 사용: RDS 도 MySQL이므로 dump 마이그레이션을 통하여 빠른 DB동기화
![Image](https://user-images.githubusercontent.com/84966961/188040971-41ebe05b-8d8e-4790-ace1-c044c8d2e965.png)
4. 2022년 1월 데이터 대략 2~30만건 로컬 DB insert

**Comment by Moveuk** [comment]
Elsasticsearch로 DB가 변경됨에 따라 데이터 저장 관련 이슈 종료.
